import { SweetItem, ReviewItem } from "./types";

// Images are in /public folder (root level) - no imports needed in Vite
export const IMAGES = {
  hero: "/sweets.jpg",
  kajuKatli: "/katli.jpg",
  gulabJamun: "/jamun.jpg",
  laddu: "/laddu.jpg",
  giftBox: "/gift box.jpg",
  rasgulla: "/rasgulla.jpg",
  kesarBarfi: "/barfi.jpg",
  peda: "/peda.jpg",
  jalebi: "/jalebi.avif",
  ghee: "/ghee.jpg",
};

export const SWEETS_DATA: SweetItem[] = [
  {
    id: "1",
    name: "काजू कतली",
    englishName: "Kaju Katli",
    description: "Premium melt-in-your-mouth cashew fudge prepared with pure ingredients, topped with edible silver foil.",
    category: "indian-sweets",
    image: IMAGES.kajuKatli,
    isPopular: true,
  },
  {
    id: "2",
    name: "गुलाब जामुन",
    englishName: "Gulab Jamun",
    description: "Soft, spongy mawa dumplings fried to golden perfection and soaked in warm cardamom infused sugar syrup.",
    category: "indian-sweets",
    image: IMAGES.gulabJamun,
    isPopular: true,
  },
  {
    id: "3",
    name: "मोतीचूर लड्डू",
    englishName: "Motichoor Laddu",
    description: "Delectable round laddus made from fine gram flour beads fried in pure desi ghee, flavored with saffron.",
    category: "indian-sweets",
    image: IMAGES.laddu,
    isPopular: true,
  },
  {
    id: "4",
    name: "रसगुल्ला",
    englishName: "Rasgulla",
    description: "Spongy, light, and juicy white cottage cheese balls soaked in clear sweet syrup. The absolute classic.",
    category: "indian-sweets",
    image: IMAGES.rasgulla,
    isPopular: false,
  },
  {
    id: "5",
    name: "केसर बर्फी",
    englishName: "Kesar Barfi",
    description: "Traditional rich condensed milk fudge infused with exotic Kashmiri saffron and cardamom.",
    category: "indian-sweets",
    image: IMAGES.kesarBarfi,
    isPopular: false,
  },
  {
    id: "6",
    name: "मथुरा पेड़ा",
    englishName: "Peda",
    description: "Caramelized milk solids cooked traditionally with fresh mawa, sugar, and cardamoms. A pure heritage taste.",
    category: "indian-sweets",
    image: IMAGES.peda,
    isPopular: false,
  },
  {
    id: "7",
    name: "देसी घी जलेबी",
    englishName: "Jalebi",
    description: "Crispy, spiral-shaped fresh orange batters deep-fried in pure desi ghee and bathed in hot saffron syrup.",
    category: "indian-sweets",
    image: IMAGES.jalebi,
    isPopular: true,
  },
  {
    id: "8",
    name: "उत्सव मिठाई बक्सा",
    englishName: "Festival Sweets",
    description: "Customized assorted platters featuring our finest hand-crafted sweets, perfect for Diwali and personal gifting.",
    category: "special-items",
    image: IMAGES.giftBox,
    isPopular: true,
  },
  {
    id: "9",
    name: "शाही उपहार डिब्बा",
    englishName: "Premium Gift Boxes",
    description: "Exquisite royal maroon and golden gift packaging options filled with luxury dry fruits and premium bites.",
    category: "special-items",
    image: IMAGES.giftBox,
    isPopular: false,
  },
  {
    id: "10",
    name: "शादी एवं उत्सव ऑर्डर",
    englishName: "Celebration Orders",
    description: "Bulk sweet arrangements and custom catering services in Kanpur for weddings, birthdays, and family functions.",
    category: "special-items",
    image: IMAGES.giftBox,
    isPopular: true,
  },
];

export const REVIEWS_DATA: ReviewItem[] = [
  {
    id: "r1",
    name: "Piyush Sinha",
    rating: 5,
    comment: "Excellent taste and extremely fresh sweets! Their Kaju Katli and Gulab Jamun are the best in the Vijay Nagar/Shastri Nagar area. Cleanliness is highly maintained.",
    date: "1 week ago",
    tag: "Local Guide",
  },
  {
    id: "r2",
    name: "Amit Tiwari",
    rating: 4,
    comment: "One of the most trusted sweet shops in Kanpur. The quality of desi ghee they use is amazing, very rich taste and excellent service. Motichoor Laddu is a must-try.",
    date: "2 weeks ago",
    tag: "Regular Customer",
  },
  {
    id: "r3",
    name: "Roshni Gupta",
    rating: 5,
    comment: "We always order our wedding and festival gift boxes from Rahul Sweets & Namkeen. The packaging is absolutely premium and luxury level. Highly recommended!",
    date: "1 month ago",
    tag: "Verified Buyer",
  },
  {
    id: "r4",
    name: "Sandeep Mishra",
    rating: 4.5,
    comment: "Fresh quality, hygienic preparation, and friendly staff. Conveniently located in Shastri Nagar. Their Jalebi in the morning is highly delicious.",
    date: "1 month ago",
    tag: "Local Resident",
  },
];